### ISSUE TITLE
Noobie question about spotify connect

### ISSUE THREAD

**Issue by odyslam** [plietar/librespot#111]
Hey,

I searched both the docs and the questions here on the project but I couldn't find a clear answer. I

Is it possible to use this library as an interface to control a spotify connect device (Pc) from a python script on another device(Rpi2)? (e.g play specific playlists etc)

Thank you for you time folks,
Cheers!

**Comment by SimonTeixidor** [comment]
It is possible! It might be a bit tricky to call the rust code from python though.

I'm working on a HTTP API around this library so that it can easily be used from any language, although I have very little time to work on it.  I pushed an initial commit tonight, at the very least it should give you an idea of how it is done: https://github.com/Spotifyd/spotifyd-http.

**Comment by plietar** [comment]
Like @SimonPersson said, this library can be used both to play music and control devices, although the latter hasn't been the main focus so far.

You may want to look at [spotcontrol](https://github.com/badfortrains/spotcontrol) which is a re-implementation of librespot in Go, focused on the control part.

In any case, calling from python may be tricky, and the easiest solution is to wrap librespot or spotcontrol in an HTTP service (like @SimonPersson has done) and call it from your python script.

**Comment by odyslam** [comment]
spotifyd-http seems pretty cool, if only I could contribute :P
