### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by kyrias** [plietar/librespot#130]
When started in discovery mode any client can connect, but then it'll cache the credentials and will only show up for clients connected to that account.  Would it be possible for the librespot client to keep showing up for other clients, and have them be able to connect to it instead, "kicking out" the first user?  Would be very useful to have on my media laptop, so both me and my SO can stream to it.

**Comment by plietar** [comment]
The way librespot is designed at the moment makes this hard to do. It's incapable of reconnecting without a restart.

I've been working on a (partial) rewrite which, among other things, enables this. I'll push my current WIP soon.

**Comment by kyrias** [comment]
Cool, hopefully it'll be possible soon then.  (And I really like this project, so thanks!)

**Comment by plietar** [comment]
I've just pushed branch v0.2, which contains the said rewrite. I don't have a second account around so I can't really test, but it *should* work. You'll probably need a nightly rust to try it.

```shell
$ cargo run --name Device --discovery
```

There's probably some rough edges. Seeking and caching don't work yet. Oh and the AP is hardcoded to London, change https://github.com/plietar/librespot/blob/v0.2/src/connection/mod.rs#L68 if you don't live around there (use the first value from https://apresolve.spotify.com/).

If your run into any issues, please let me know, preferably on [gitter](https://gitter.im/sashahilton00/spotify-connect-resources) rather than creating a new issue since this is still a WIP.

**Comment by pkonecki** [comment]
@kyrias I've worked around the issue by running two instances with different cache locations. I've also used different names as a precaution, but I'm not sure it's necessary. I use alsa as backend and I've had no problem switching from one to the other instance.

**Comment by sashahilton00** [comment]
I have been thinking a little about this, as it's moderately irritating having to restart and delete the json in the cache whenever someone wants to switch, and whilst I don't know the scale of the rewrite required to implement this, I seem to remember seeing some code for internally restarting rust programs that went something like this:

```
fn main() {
    while run() {
        // Insert code here.
    }
}
fn run() -> bool {
    // Trigger restart here.
}
```

Would this be a possible (temporary) solution to adding multi account support to librespot without a significant rewrite? What I was thinking is that one could pass something like a -m flag to enable multi account support, whereby upon a client disconnecting the credentials.json file in the cache (or whatever it's called) is deleted, and librespot gets restarted internally. Is that something that is potentially workable?

**Comment by crg-n** [comment]
This is still something I am very interested in too! As v0.2 has been abandoned what is likelihood of getting multiple account support on the master branch either natively or using Sasha's suggested workaround? Any thoughts @plietar ?

**Comment by plietar** [comment]
This should be working now.
There may be some rough edges, so please test and let me know how it goes
