### ISSUE TITLE
Add alsa as audio backend

### ISSUE THREAD

**Issue by joerg-krause** [plietar/librespot#63]
The portaudio backend results in heavy CPU load on embedded Linux systems. There already exists a branch with a very basic alsa backend. As a first test showed that on an ARMv5 board the CPU load was reduced from about 80% with portaudio to about 25% with alsa I would really like to see the alsa backend as default or optional backend for any Linux system.

So, what has to be done?

**Comment by plietar** [comment]
Thanks for opening an issue to track this,
On the ALSA side, the bindings need fixing, they at least have a problem with 32/64 bit. Also the API they expose isn't great.

On the librespot side, I'd like to change how audio backend are organised before adding the ALSA and gstreamer ones. Instead of being chosen at compile time based on various heuristics, it should be possible to include multiple backends and choose at runtime with a command line flag.

**Comment by joerg-krause** [comment]
Fur those who are interested in an ALSA backend, I ported the alsa branch from @plietar https://github.com/plietar/librespot/tree/alsa  to my fork: https://github.com/joerg-krause/librespot.

**Comment by herrernst** [comment]
Thanks! Would be great if this could get merge sometime. Using ALSA makes cross-compiling for Linux easier because you don't need pkg-config anymore.

**Comment by plietar** [comment]
Exams finish on Wednesday :smile: I'll have more time after that to merge it into master

**Comment by herrernst** [comment]
Any news on that? Thanks!
