### ISSUE TITLE
Inquiry on the Protobufs

### ISSUE THREAD

**Issue by scraduff** [plietar/librespot#90]
Hi,

I was just wondering if you could say where you got the protobufs from? The client, as far as I can see, doesn't contain them and they don't seem to be pulled off a server either.

Cheers

**Comment by plietar** [comment]
They come from various sources.
At the very beginning I just guessed them based on the packet dumps.

The desktop client contains a description of most of them in compiled form inside the binary, including the name of the fields (the libraries also have them I think, can't really remember).

The web client also has the "high level" protobufs, which is pretty much every thing but key exchange and authentication is missing, since there aren't relevant to that client.

In both cases, the protobufs are not in the original form, but encoded in some binary/json representation inside the clients. I have a couple of scripts to extract them

**Comment by scraduff** [comment]
That's great, just wanted to know there wasn't an easy way I was missing.

Yeah I though they looked pretty similar to the web versions.

**Comment by plietar** [comment]
No worries.
Btw, for that kind of question there is a gitter chat room which is more appropriate:
https://gitter.im/sashahilton00/spotify-connect-resources
